### ISSUE TITLE
Rich text areas always report themselves as dirty

### ISSUE THREAD

**Issue by jadefish** [rx/presenters#110]
**Describe the bug**
Rich text areas with initial values report as dirty before any changes have been made.

**To Reproduce**
1. Create a rich text area with an initial value:
```ruby
content do
  rich_text_area do
    value 'here is some default text'
  end

  button :cancel do
    event :click do
      prompt_if_dirty :some_dialog
      # ...
    end
  end
end
```

2. Click the cancel button to run the `prompt_if_dirty` check

**Expected behavior**
The `prompt_if_dirty` check should not invoke `:some_dialog`.

**Desktop:**
 - OS: macOS 10.14 Mojave
 - Browser: Chrome
 - Version: 72

**Comment by nick-geotix** [comment]
Fixed with #134.
