### ISSUE TITLE
Toggle label is misaligned

### ISSUE THREAD

**Issue by jadefish** [rx/presenters#67]
The label element contained within toggle components is misaligned when embedded in an element smaller than 12 column-widths:

<img width="480" alt="screen shot 2018-11-08 at 13 50 14" src="https://user-images.githubusercontent.com/29804640/48220947-b0f3d180-e35e-11e8-8d55-3c03ed565140.png">

```ruby
dialog width: '30rem' do
  form do
    switch name: :reset_password_email, checked: true, text: 'Send reset password email'
  end
end
```

When contained within a column of size 12, the label lacks any leading space:

<img width="370" alt="screen shot 2018-11-08 at 13 57 54" src="https://user-images.githubusercontent.com/29804640/48220988-ce28a000-e35e-11e8-84e1-58bf9b8a977b.png">

```ruby
grid do
  column size: 12 do
    switch name: :reset_password_email, checked: true, text: 'Send reset password email'
  end
end
```

**Comment by rx** [comment]
This is fixed on the rx branch.
